name: deployment

on:
  issues:
    types: [opened, labeled]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'sftp-user') || contains(github.event.label.name, 'sftp-user')
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Event Payload
        run: |
          echo "Event payload:"
          echo ${{ toJson(github.event) }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533266989803:role/sftp-github-role
          role-session-name: github-session
          aws-region: us-east-1

      - name: Extract Issue Details
        id: issue_details
        run: |
          echo "USERNAME=$(echo '${{ github.event.issue.body }}' | jq -r '.[] | select(.id=="username") | .value')" >> $GITHUB_ENV
          echo "DELETION_DATE=$(echo '${{ github.event.issue.body }}' | jq -r '.[] | select(.id=="deletion_date") | .value')" >> $GITHUB_ENV
          echo "LOCATIONS=$(echo '${{ github.event.issue.body }}' | jq -r '.[] | select(.id=="locations") | .value')" >> $GITHUB_ENV

      - name: Run Script to Create SFTP User
        run: |
          bash createsftpusernew.sh

