name: Create SFTP User

on:
  push:
    branches:
      - main

jobs:
  create_user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Run Script to Create SFTP User
        run: |
          bash createsftpusernew.sh 

