name: deployment

on:
  issues:
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.labels.*.name contains 'sftp-user'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533266989803:role/sftp-github-role
          role-session-name: github-session
          aws-region: us-east-1

      - name: Extract Issue Details
        id: issue_details
        run: |
          echo "USERNAME=${{ github.event.issue.body | fromJson | select(.fields | .username) }}" >> $GITHUB_ENV
          echo "DELETION_DATE=${{ github.event.issue.body | fromJson | select(.fields | .deletion_date) }}" >> $GITHUB_ENV
          echo "LOCATIONS=${{ github.event.issue.body | fromJson | select(.fields | .locations) }}" >> $GITHUB_ENV

      - name: Run Script to Create SFTP User
        run: |
          bash createsftpusernew.sh

